export const SET_MINTED_COUNT = "SET_MINTED_COUNT";
export const SET_MINTER_LOADER = "SET_MINTER_LOADER";

export const SET_ETH_PRICE = "SET_ETH_PRICE";
export const SET_WALLET_CONNECTIVITY = "SET_WALLET_CONNECTIVITY";
export const SET_WALLET_LOADER = "SET_WALLET_LOADER";
